version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: announcementdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./SellUp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./SellUp:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=announcementdb
      - DB_USER=postgres
      - DB_PASSWORD=1
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build: ./sell-up-ui
    command: npm start
    volumes:
      - ./sell-up-ui:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
