# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
commands = [
  "pip install -r requirements.txt",
  "cd sell-up-ui && npm install"
]

[phases.build]
commands = [
  "cd sell-up-ui && npm run build"
]

[start]
cmd = "python manage.py runserver 0.0.0.0:8000"
