# Generated by Django 4.2.20 on 2025-04-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
