# Generated by Django 4.2.20 on 2025-05-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('range', 'Range')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'FilterAttributes',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='filter_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='listings.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_category_name'),
        ),
        migrations.AddField(
            model_name='filterattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='listings.category'),
        ),
        migrations.AlterUniqueTogether(
            name='filterattribute',
            unique_together={('name', 'category')},
        ),
    ]
